export const products = [
  {
    coverImage: './assets/img/cycle1.png',
    mainImage: './assets/img/cycle2.jpg',
    name: '自転車',
    description: 'サイクリングを楽しもう',
    heding1: 'メリット1：ごはんがおいしい',
    heding2: 'メリット2：身体に負担が少ない',
    heding3: 'メリット3：足は細くなる',
    headingtext1: '食べて痩せる事は健康である',
    headingtext2: '膝の故障もランニングより少ない',
    headingtext3: '美脚を手に入れたい方にピッタリ',
  },
  {
    coverImage: './assets/img/run1.png',
    mainImage: './assets/img/run2.jpg',
    name: 'ラン、トレイルラン',
    description: '走ってみよう',
    heding1: 'メリット1：必要道具は最低限',
    heding2: 'メリット2：自然を走る気持ちよさ',
    heding3: 'メリット3：終わった後の達成感',
    headingtext1: 'ランニングシューズさえあれば手軽に楽しめる',
    headingtext2: 'トレイルランは自然を走るので気持ちがいい',
    headingtext3: '疲れた後の温泉は最高',
  },
  {
    coverImage: './assets/img/yama1.png',
    mainImage: './assets/img/yama2.jpg',
    name: '登山',
    description: '山に登ろう',
    heding1: 'メリット1：景色がいい',
    heding2: 'メリット2：自然の偉大さを知る',
    heding3: 'メリット3：心が強くなる',
    headingtext1: '稜線は遮るものが無く見渡す限り絶景',
    headingtext2: '時には荒れて自然にはかなわないと知る',
    headingtext3: 'ツラくなった時に頼れるのは自分だけ',
  },
  {
    coverImage: './assets/img/bike1.png',
    mainImage: './assets/img/bike2.jpg',
    name: 'オフロードバイク',
    description: 'エンデューロ',
    heding1: 'メリット1：アクセルをぶん回す快感',
    heding2: 'メリット2：オンロードには無い世界観',
    heding3: 'メリット3：体感が強化される',
    headingtext1: 'コースに行けば道路交通法は無い。思いっきりぶん回そう',
    headingtext2: 'ダートは舗装路のように走れない。バイクを取りまわす楽しさ',
    headingtext3: 'ダートの上でバランスを取るのは至難の業。体感が強くなる',
  },
];
